export { default as Faceb } from "./Faceb.png";
export { default as whatsup } from "./whatsup.png";
export { default as inst } from "./inst.png";
export { default as skype } from "./skype.png";
export { default as youtube } from "./youtube.png";
export { default as card1 } from "./card1.png";
export { default as card2 } from "./card2.png";
export { default as card3 } from "./card3.png";
export { default as card4 } from "./card4.png";
export { default as card5 } from "./card5.png";
// export { default as image5 } from "../image/tv/image5.jpg";
